In [2]:
import numpy as np

In [5]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [10]:



x = np.array([2,3,5,1,2,4])
print(x)
print('total elements =>',x.shape)
print('dimension wise elements=>',x.shape)
print('dimension count',x.ndim)

[2 3 5 1 2 4]
total elements => (6,)
dimension wise elements=> (6,)
dimension count 1


In [11]:
y = np.array([[2,3,5],[1,2,4]])
print(y)
print('total elements =>',y.shape)
print('dimension wise elements=>',y.shape)
print('dimension count',y.ndim)

[[2 3 5]
 [1 2 4]]
total elements => (2, 3)
dimension wise elements=> (2, 3)
dimension count 2


In [17]:
z = np.array([[2,3,5],[1,2,4],[8,9,5]])
print(z)
print('total elements =>',z.size)
print('dimension wise elements=>',z.shape)
print('dimension count',z.ndim)

[[2 3 5]
 [1 2 4]
 [8 9 5]]
total elements => 9
dimension wise elements=> (3, 3)
dimension count 2


In [ ]:
x=[1,2,3,4,5,6,7,8]
z=np.array