In [2]:
import numpy as np

In [5]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [10]:



x = np.array([2,3,5,1,2,4])
print(x)
print('total elements =>',x.shape)
print('dimension wise elements=>',x.shape)
print('dimension count',x.ndim)

[2 3 5 1 2 4]
total elements => (6,)
dimension wise elements=> (6,)
dimension count 1


In [11]:
y = np.array([[2,3,5],[1,2,4]])
print(y)
print('total elements =>',y.shape)
print('dimension wise elements=>',y.shape)
print('dimension count',y.ndim)

[[2 3 5]
 [1 2 4]]
total elements => (2, 3)
dimension wise elements=> (2, 3)
dimension count 2


In [17]:
z = np.array([[2,3,5],[1,2,4],[8,9,5]])
print(z)
print('total elements =>',z.size)
print('dimension wise elements=>',z.shape)
print('dimension count',z.ndim)

[[2 3 5]
 [1 2 4]
 [8 9 5]]
total elements => 9
dimension wise elements=> (3, 3)
dimension count 2


In [18]:
x=[1,2,3,4,5,6,7,8]
z=np.array([[x,x,x],[x,x,x],[x,x,x]])
print('shape',z.shape)
print(z)

shape (3, 3, 8)
[[[1 2 3 4 5 6 7 8]
  [1 2 3 4 5 6 7 8]
  [1 2 3 4 5 6 7 8]]

 [[1 2 3 4 5 6 7 8]
  [1 2 3 4 5 6 7 8]
  [1 2 3 4 5 6 7 8]]

 [[1 2 3 4 5 6 7 8]
  [1 2 3 4 5 6 7 8]
  [1 2 3 4 5 6 7 8]]]


In [26]:
d = np.arange(-10,11,.5)
d.shape

(42,)

In [27]:
d.reshape(6,7)

array([[-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ],
       [ -6.5,  -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5],
       [ -3. ,  -2.5,  -2. ,  -1.5,  -1. ,  -0.5,   0. ],
       [  0.5,   1. ,   1.5,   2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ],
       [  7.5,   8. ,   8.5,   9. ,   9.5,  10. ,  10.5]])

In [28]:
d.reshape(2,3,7)

array([[[-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ],
        [ -6.5,  -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5],
        [ -3. ,  -2.5,  -2. ,  -1.5,  -1. ,  -0.5,   0. ]],

       [[  0.5,   1. ,   1.5,   2. ,   2.5,   3. ,   3.5],
        [  4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ],
        [  7.5,   8. ,   8.5,   9. ,   9.5,  10. ,  10.5]]])

In [32]:
a = np.linspace(1,1000,100)
a

array([   1.        ,   11.09090909,   21.18181818,   31.27272727,
         41.36363636,   51.45454545,   61.54545455,   71.63636364,
         81.72727273,   91.81818182,  101.90909091,  112.        ,
        122.09090909,  132.18181818,  142.27272727,  152.36363636,
        162.45454545,  172.54545455,  182.63636364,  192.72727273,
        202.81818182,  212.90909091,  223.        ,  233.09090909,
        243.18181818,  253.27272727,  263.36363636,  273.45454545,
        283.54545455,  293.63636364,  303.72727273,  313.81818182,
        323.90909091,  334.        ,  344.09090909,  354.18181818,
        364.27272727,  374.36363636,  384.45454545,  394.54545455,
        404.63636364,  414.72727273,  424.81818182,  434.90909091,
        445.        ,  455.09090909,  465.18181818,  475.27272727,
        485.36363636,  495.45454545,  505.54545455,  515.63636364,
        525.72727273,  535.81818182,  545.90909091,  556.        ,
        566.09090909,  576.18181818,  586.27272727,  596.36363

In [37]:
d = np.random.randint(1,6,(10,10))
print(d)

[[5 3 2 4 5 1 5 2 5 4]
 [1 4 5 1 2 3 1 5 3 3]
 [1 2 3 2 2 5 2 3 4 3]
 [4 1 4 2 3 1 3 2 3 2]
 [2 5 2 5 4 1 1 4 1 4]
 [5 5 4 5 1 1 3 4 3 4]
 [1 5 5 5 2 4 1 4 1 4]
 [1 4 1 4 2 1 5 3 4 2]
 [2 5 2 2 4 1 3 3 4 3]
 [5 3 1 2 5 1 5 5 1 3]]


In [40]:
d[-1]

array([5, 3, 1, 2, 5, 1, 5, 5, 1, 3])

In [42]:
d[0,0] # d[0][0]

5

In [44]:
d[3,5]

1

In [45]:
d[:,0] # all rows of column idx 0

array([5, 1, 1, 4, 2, 5, 1, 1, 2, 5])

In [46]:
d[:,-3]

array([2, 5, 3, 2, 4, 4, 4, 3, 3, 5])

In [47]:
d[:5,2] # first five rows of column idx 2

array([2, 5, 3, 4, 2])

In [49]:
d[:5,:5] # ?

array([[5, 3, 2, 4, 5],
       [1, 4, 5, 1, 2],
       [1, 2, 3, 2, 2],
       [4, 1, 4, 2, 3],
       [2, 5, 2, 5, 4]])

In [51]:
x = np.random.randint(1,10,(3,3))
y = np.random.randint(1,10,(3,3))
print(x,'\n',y)

[[1 3 6]
 [2 7 8]
 [4 5 2]] 
 [[4 4 1]
 [8 6 7]
 [4 1 8]]


In [52]:
x+y



array([[ 5,  7,  7],
       [10, 13, 15],
       [ 8,  6, 10]])

In [53]:
x*y

array([[ 4, 12,  6],
       [16, 42, 56],
       [16,  5, 16]])

In [54]:
x-y

array([[-3, -1,  5],
       [-6,  1,  1],
       [ 0,  4, -6]])

In [57]:
x + 10

array([[11, 13, 16],
       [12, 17, 18],
       [14, 15, 12]])

In [58]:
np.dot(x,y)

array([[ 52,  28,  70],
       [ 96,  58, 115],
       [ 64,  48,  55]])

In [59]:
np.multiply(x,y)

array([[ 4, 12,  6],
       [16, 42, 56],
       [16,  5, 16]])

In [60]:
np.matmul(x,y)

array([[ 52,  28,  70],
       [ 96,  58, 115],
       [ 64,  48,  55]])

In [62]:
x * y

array([[ 4, 12,  6],
       [16, 42, 56],
       [16,  5, 16]])

In [63]:
np.cross(x,y)

array([[-21,  23,  -8],
       [  1,  50, -44],
       [ 38, -24, -16]])

In [64]:
np.hstack([x,y])

array([[1, 3, 6, 4, 4, 1],
       [2, 7, 8, 8, 6, 7],
       [4, 5, 2, 4, 1, 8]])

In [65]:
np.vstack([x,y])

array([[1, 3, 6],
       [2, 7, 8],
       [4, 5, 2],
       [4, 4, 1],
       [8, 6, 7],
       [4, 1, 8]])

In [67]:
np.append(x,[1,2,3])

array([1, 3, 6, 2, 7, 8, 4, 5, 2, 1, 2, 3])

In [69]:
np.append(x,y,axis=0)

array([[1, 3, 6],
       [2, 7, 8],
       [4, 5, 2],
       [4, 4, 1],
       [8, 6, 7],
       [4, 1, 8]])

In [72]:
x.max(axis=0)

array([4, 7, 8])

In [74]:
x.min(axis=1)

array([1, 2, 2])

In [75]:
x.flatten()

array([1, 3, 6, 2, 7, 8, 4, 5, 2])

In [77]:
d [d>3] # boolean filter

array([5, 4, 5, 5, 5, 4, 4, 5, 5, 5, 4, 4, 4, 5, 5, 4, 4, 4, 5, 5, 4, 5,
       4, 4, 5, 5, 5, 4, 4, 4, 4, 4, 5, 4, 5, 4, 4, 5, 5, 5, 5])

In [79]:
d[d==1] # give all the ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [80]:
d>3

array([[ True, False, False,  True,  True, False,  True, False,  True,
         True],
       [False,  True,  True, False, False, False, False,  True, False,
        False],
       [False, False, False, False, False,  True, False, False,  True,
        False],
       [ True, False,  True, False, False, False, False, False, False,
        False],
       [False,  True, False,  True,  True, False, False,  True, False,
         True],
       [ True,  True,  True,  True, False, False, False,  True, False,
         True],
       [False,  True,  True,  True, False,  True, False,  True, False,
         True],
       [False,  True, False,  True, False, False,  True, False,  True,
        False],
       [False,  True, False, False,  True, False, False, False,  True,
        False],
       [ True, False, False, False,  True, False,  True,  True, False,
        False]])